// Данные для статей 6-50 (заг ружаются по требованию)
const REMAINING_ARTICLES = [
    { title: "Allies of Kyrgyzstan's strongman president sweep snap parliamentary election", url: "https://www.reuters.com/world/asia-pacific/allies-kyrgyzstans-president-win-majority-parliamentary-election-preliminary-2025-11-30/" },
    { title: "Allies of Kyrgyzstan's president set to win snap parliamentary election", url: "https://www.reuters.com/business/media-telecom/allies-kyrgyzstans-president-set-win-snap-parliamentary-election-2025-11-29" },
    { title: "Kyrgyzstan bans top independent media as 'extremist' in pre-election crackdown", url: "https://www.reuters.com/business/media-telecom/kyrgyzstan-bans-top-independent-media-extremist-pre-election-crackdown-2025-10-28" },
    { title: "Kyrgyz leader seeks death penalty for worst crimes against children and women", url: "https://www.reuters.com/world/asia-pacific/kyrgyz-leader-seeks-death-penalty-worst-crimes-against-children-women-2025-10-01" },
    { title: "Kyrgyz parliament backs new state controls on media outlets", url: "https://www.reuters.com/business/media-telecom/kyrgyz-parliament-backs-new-state-controls-media-outlets-2025-06-26" },
    { title: "Kyrgyzstan court jails two journalists for undermining public order", url: "https://www.reuters.com/business/media-telecom/kyrgyzstan-court-jails-two-journalists-undermining-public-order-2025-09-17" },
    { title: "Kyrgyzstan criticises EU sanctions on its banks over Russia links, calls for dialogue", url: "https://www.reuters.com/world/kyrgyzstan-criticises-eu-sanctions-its-banks-over-russia-links-calls-dialogue-2025-10-24" },
    { title: "Kyrgyzstan authorities detain opposition figures ahead of snap election", url: "https://www.reuters.com/business/media-telecom/kyrgyzstan-authorities-detain-opposition-figures-ahead-snap-election-2025-11-22" },
    { title: "Kyrgyzstan launches $50 million of tokens in national stablecoin", url: "https://www.reuters.com/world/asia-pacific/kyrgyzstan-launches-50-million-tokens-national-stablecoin-2025-11-12" },
    { title: "Melting Kara-Batkak Glacier highlights looming water woes", url: "https://eurasianet.org/melting-kara-batkak-glacier-highlights-looming-water-woes" },
    { title: "The silent crisis: Abortion and reproductive rights in Turkmenistan", url: "https://eurasianet.org/the-silent-crisis-abortion-and-reproductive-rights-in-turkmenistan" },
    { title: "From Foe to Partner? Russia's Rapprochement with the Taliban and its Regional Implications", url: "https://www.cacianalyst.org/publications/analytical-articles/item/13872-from-foe-to-partner" },
    { title: "The Taliban's Diplomatic and Economic Expansion in Central Asia", url: "https://www.cacianalyst.org/publications/analytical-articles/item/13850-the-new-russia-iran-treaty-implications-for-the-south-caucasus-region.html" },
    { title: "Kyrgyzstan and Tajikistan Resolve Final Border Dispute: A Historic but Fragile Peace", url: "https://www.cacianalyst.org/publications/analytical-articles/item/13868-kyrgyzstan-and-tajikistan-resolve-final-border-dispute-a-historic-but-fragile-peace.html" },
    { title: "Samarkand Summit Signals a New Era for EU-Central Asia Energy Ties", url: "https://www.turancenter.org/analysis/samarkand-summit-signals-a-new-era-for-eu-central-asia-energy-ties" },
    { title: "North, South, and the Tandem: Understanding Kyrgyzstan's 2025 Parliamentary Elections", url: "https://www.turancenter.org/analysis/north-south-and-the-tandem-understanding-kyrgyzstans-2025-parliamentary-elections" },
    { title: "Keeping Kyrgyz Journalism Afloat While the Island of Democracy Sinks", url: "https://thediplomat.com/2024/06/keeping-kyrgyz-journalism-afloat-while-the-island-of-democracy-sinks" },
    { title: "Kyrgyzstan's Vape Ban: Clean Lungs or Dirty Lobbying?", url: "https://thediplomat.com/2024/11/kyrgyzstans-vape-ban-clean-lungs-or-dirty-lobbying" },
    { title: "Kazakh court jails former minister for 24 years for brutal murder of wife", url: "https://www.theguardian.com/global-development/article/2024/may/14/kazakh-court-jails-former-minister-for-24-years-for-brutal-of-wife" },
    { title: "In Kyrgyzstan, an 'unprecedented crackdown' on free press raises alarm", url: "https://www.aljazeera.com/features/2024/7/18/in-kyrgyzstan-an-unprecedented-crackdown-on-free-press-raises-alarm" },
    { title: "\"Green Legacy\" of Kyrgyzstan Turns into Desert", url: "https://longreads.cabar.asia/jashylmuras" },
    { title: "The women keep being killed. Why does Kyrgyzstan not recognize femicide at the legislative level?", url: "https://cabar.asia/en/the-women-keep-being-killed-why-does-kyrgyzstan-not-recognize-femicide-at-the-legislative-level" },
    { title: "Sabotaging the Nature: Introduction of Altai Elks to Kyrgyzstan May Eradicate Tien Shan Elks", url: "https://cabar.asia/en/sabotaging-the-nature-introduction-of-altai-elks-to-kyrgyzstan-may-eradicate-tien-shan-elks" },
    { title: "Non-prohibited marketing: how TV advertising contributes to the obesity of children in Kyrgyzstan", url: "https://cabar.asia/en/non-prohibited-marketing-how-tv-advertising-contributes-to-the-obesity-of-children-in-kyrgyzstan" },
    { title: "The Wakhan Corridor: China's Inroad to Afghanistan", url: "https://www.cacianalyst.org/publications/analytical-articles/item/13827-thewakhan-corridor-chinas-inroad-to-afghanistan.html" },
    { title: "Women in Central Asia Lead on Climate Change", url: "https://iwpr.net/global-voices/women-central-asia-lead-climate-change" },
    { title: "'Why must we be silent?': horrific attack in Kyrgyzstan puts focus on violence against women", url: "https://www.theguardian.com/global-development/2023/oct/27/why-must-we-be-silent-horrific-attack-in-kyrgyzstan-puts-focus-on-violence-against-women" },
    { title: "Kyrgyzstan: Bishkek banks on China's gas-powered buses to clean air", url: "https://eurasianet.org/kyrgyzstan-bishkek-banks-on-chinas-gas-powered-buses-to-clean-air" },
    { title: "Kyrgyzstan allowing indigenous horses to die out, breeders complain", url: "https://eurasianet.org/kyrgyzstan-allowing-indigenous-horses-to-die-out-breeders-complain" },
    { title: "Suicide attempts raise alarm over shaming women in Kyrgyzstan", url: "https://www.aljazeera.com/features/2022/1/25/kyrgyzstan-women-harassment" },
    { title: "The rights defender who dared challenge Kyrgyzstan's security services", url: "https://eurasianet.org/the-rights-defender-who-dared-challenge-kyrgyzstans-security-services" },
    { title: "Facing down threats, Kyrgyz YouTube show fights for food safety", url: "https://eurasianet.org/facing-down-threats-kyrgyz-youtube-show-fights-for-food-safety" },
    { title: "Kyrgyzstan: Rights lawyer gets reprieve in high-profile case", url: "https://eurasianet.org/kyrgyzstan-rights-lawyer-gets-reprieve-in-high-profile-case" },
    { title: "Russian press attacking Kyrgyzstan's leaders", url: "https://eurasianet.org/russian-press-attacking-kyrgyzstans-leaders" },
    { title: "In Kyrgyzstan's 'graveyard of factories' locals fear chemical time bomb", url: "https://eurasianet.org/in-kyrgyzstans-graveyard-of-factories-locals-fear-chemical-time-bomb" },
    { title: "Kyrgyzstan: Rights still on hold for disabled citizens", url: "https://eurasianet.org/kyrgyzstan-rights-still-on-hold-for-disabled-citizens" },
    { title: "What Happened at the Kyrgyz-Tajik Border?", url: "https://thediplomat.com/2021/06/what-happened-at-the-kyrgyz-tajik-border" },
    { title: "Handful of Afghans who fled to Kyrgyzstan face uncertain futures", url: "https://www.aljazeera.com/news/2021/12/15/handful-of-afghans-who-fled-to-kyrgyzstan-face-uncertain-futures" },
    { title: "Kyrgyzstan: Family of 'bride kidnapping' victim seek justice", url: "https://www.aljazeera.com/news/2021/4/27/we-want-justice-family-of-murdered-kyrgyz-woman-demand-change" },
    { title: "Kyrgyzstan moves to nationalise gold mine run by Canadian company", url: "https://www.aljazeera.com/news/2021/7/9/kyrgyzstan-moves-to-nationalise-gold-mine-run-by-canadian-company" },
    { title: "Digital education lags behind as Kyrgyzstan's schools lack access", url: "https://globalvoices.org/2021/07/23/digital-education-lags-behind-as-kyrgyzstans-schools-lack-access" },
    { title: "What Kyrgyzstan's hasty transition to presidential governance says about the state of its democracy", url: "https://globalvoices.org/2021/02/03/what-kyrgyzstans-hasty-transition-to-presidential-governance-says-about-the-state-of-its-democracy" },
    { title: "Kyrgyzstan's journalists fear yet another hurdle to freedom of speech", url: "https://globalvoices.org/2020/06/26/kyrgyzstans-journalists-fear-yet-another-hurdle-to-freedom-of-speech" },
    { title: "Post-election protests spark another revolution in Kyrgyzstan", url: "https://globalvoices.org/2020/10/06/post-election-protests-spark-another-revolution-in-kyrgyzstan" },
    { title: "Kyrgyzstan's civil society mobilises to fight COVID-19", url: "https://globalvoices.org/2020/04/09/kyrgyzstans-civil-society-mobilises-to-fight-covid-19" }
];
